# Generated by Django 5.2.4 on 2025-07-07 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_hashtag_post_hashtags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_likes', models.BooleanField(default=True, help_text='Get notified when someone likes your posts')),
                ('notify_comments', models.BooleanField(default=True, help_text='Get notified when someone comments on your posts')),
                ('notify_shares', models.BooleanField(default=True, help_text='Get notified when someone shares your posts')),
                ('notify_follows', models.BooleanField(default=True, help_text='Get notified when someone follows you')),
                ('notify_mentions', models.BooleanField(default=True, help_text='Get notified when someone mentions you')),
                ('notify_messages', models.BooleanField(default=True, help_text='Get notified when someone sends you a message')),
                ('email_notifications', models.BooleanField(default=False, help_text='Receive email notifications')),
                ('notification_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='immediate', help_text='How often to receive notifications', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Settings',
                'verbose_name_plural': 'Notification Settings',
            },
        ),
    ]
